<table width="100%" border="0" cellspacing="0" cellpadding="2">
  <tr>
    <td><h3>graphic design </h3></td>
    <td width="120"><div align="right"><a href="javascript: history.go(-1)">&#8249; back</a> | <a href="/graphicdesign-home.asp">&laquo; home</a></div></td>
  </tr>
  <tr>
    <td colspan="2"><a href="/graphicdesign-logos.asp">logos</a> | <a href="#">reports</a> | <a href="#">stationery</a> | <a href="#">business
        cards</a> | <a href="#">signage</a> | <a href="#">posters</a> | <a href="#">brochures</a> | <a href="#">rollup
        banners</a></td>
    </tr>
</table>