<div class="pd_menu_01 ">
                <ul>
                  <li><a href="../index.htm">Home
                        <!--[if IE 7]><!-->
                    </a>
                      <!--<![endif]-->
                      <!--[if IE]><table><tr><td><![endif]-->
                      <!--[if IE]></td></tr></table></a><![endif]-->
                  </li>
                  <li><a href="#">Graphic Design...
                        <!--[if IE 7]><!-->
                    </a>
                      <!--<![endif]-->
                      <!--[if IE]><table><tr><td><![endif]-->
                      <ul>
                        <li>
                          <div align="left"><a href="#">Logos</a></div>
                        </li><li>
                          <div align="left"><a href="#">Reports</a></div>
                        </li><li>
                          <div align="left"><a href="#">Stationery</a></div>
                        </li><li>
                          <div align="left"><a href="#">Business Cards</a></div>
                        </li><li>
                          <div align="left"><a href="#">Signage</a></div>
                        </li><li>
                          <div align="left"><a href="#">Posters</a></div>
                        </li><li>
                          <div align="left"><a href="#">Brochures</a></div>
                        </li><li>
                          <div align="left"><a href="#">Rollup Banners</a></div>
                        </li></ul>
                      <!--[if IE]></td></tr></table></a><![endif]-->
                  </li>
                  <li><a href="../services.htm">Consultancy Services...<!--[if IE 7]><!-->
                    </a>
                      <!--<![endif]-->
                      <!--[if IE]><table><tr><td><![endif]-->
                     <ul><li>
                          <div align="left"><a href="#">Communications</a></div>
                        </li><li>
                          <div align="left"><a href="#">Corporate Image</a></div>
                        </li><li>
                          <div align="left"><a href="#">Website Evaluation</a></div>
                        </li></ul>
						<!--[if IE]></td></tr></table></a><![endif]-->
                  </li>
                  <li><a href="../events.htm">Interactive (multi)Media...
                        <!--[if IE 7]><!-->
                    </a>
                      <!--<![endif]-->
                      <!--[if IE]><table><tr><td><![endif]-->
                   <ul><li>
                          <div align="left"><a href="#">CDROM/DVD</a></div>
                        </li><li>
                          <div align="left"><a href="#">2D Animation</a></div>
                        </li><li>
                          <div align="left"><a href="#">3d Modelling</a></div>
                        </li><li>
                          <div align="left"><a href="#">Powerpoint Shows</a></div>
                        </li></ul>
						<!--[if IE]></td></tr></table></a><![endif]-->
                  </li>
                  <li><a href="../links.htm">Online Solutions...
                        <!--[if IE 7]><!-->
                    </a>
                      <!--<![endif]-->
                      <!--[if IE]><table><tr><td><![endif]-->
                     <ul>
                        <li>
                          <div align="left"><a href="#">Website</a></div>
                        </li><li>
                          <div align="left"><a href="#">Electronic Stationery</a></div>
                        </li><li>
                          <div align="left"><a href="#">Publications</a></div>
                        </li><li>
                          <div align="left"><a href="#">Banner Adverts</a></div>
                        </li><li>
                          <div align="left"><a href="#">Data Presentations</a></div>
                        </li></ul>
					  <!--[if IE]></td></tr></table></a><![endif]-->
                  </li>
                  <li><a href="../supporters.htm">Prepress Publishing...<!--[if IE 7]><!-->
                    </a>
                      <!--<![endif]-->
                      <!--[if IE]><table><tr><td><![endif]-->
                   <ul><li>
                          <div align="left"><a href="#">ISBN Registration</a></div>
                        </li><li>
                          <div align="left"><a href="#">Book Binding /Printing</a></div>
                        </li><li>
                          <div align="left"><a href="#">Brochure Printing</a></div>
                        </li><li>
                          <div align="left"><a href="#">Proofing</a></div>
                        </li><li>
                          <div align="left"><a href="#">Academic/Scientific Writing</a></div>
                        </li><li>
                          <div align="left"><a href="#">Annual Reports</a></div>
                        </li><li>
                          <div align="left"><a href="#">Presentations</a></div>
                        </li></ul>
				      <!--[if IE]></td></tr></table></a><![endif]-->
                  </li>
                  <li><a href="viewinfopage.asp?id=4">Portfolio...
                        <!--[if IE 7]><!-->
                    </a>
                      <!--<![endif]-->
                      <!--[if IE]><table><tr><td><![endif]-->
                  <ul><li>
                          <div align="left"><a href="#">Client List</a></div>
                        </li><li>
                          <div align="left"><a href="#">Testimonials</a></div>
                        </li><li>
                          <div align="left"><a href="#">Awards</a></div>
                        </li></ul>
				      <!--[if IE]></td></tr></table></a><![endif]-->
                  </li>
                  <li><a href="../supporting.htm">Partners/Links
                        <!--[if IE 7]><!-->
                    </a>
                      <!--<![endif]-->
                      <!--[if IE]><table><tr><td><![endif]-->
					  <!--[if IE]></td></tr></table></a><![endif]-->
					  </li>
                  <li><a href="../supporting.htm">About Us
                      <!--[if IE 7]><!-->
                  </a>
                    <!--<![endif]-->
                    <!--[if IE]><table><tr><td><![endif]-->
					
                    <!--[if IE]></td></tr></table></a><![endif]-->
					</li>
                  <li><a href="viewresources.asp">Contact Us
                        <!--[if IE 7]><!-->
                      </a>
                        <!--<![endif]-->
                        <!--[if IE]><table><tr><td><![endif]-->
						
                        <!--[if IE]></td></tr></table></a><![endif]-->
                  </li></ul>
              </div>