   <ul id="MenuBar1" class="MenuBarVertical">
          <li><a href="index1.asp">HOME</a> </li>
          <li><a href="graphicdesign-home.asp" class="MenuBarItemSubmenu">Graphic Design</a>
              <ul>
                <li><a href="graphicdesign-logos.asp">Logos</a></li>
                <li><a href="graphicdesign-reports.asp">Reports</a></li>
                <li><a href="graphicdesign-stationery.asp">Stationery</a></li>
                <li><a href="graphicdesign-cards.asp">Business Cards</a></li>
                <li><a href="graphicdesign-signage.asp">Signage</a></li>
                <li><a href="graphicdesign-posters.asp">Posters</a></li>
                <li><a href="graphicdesign-brochures.asp">Brochures</a></li>
                <li><a href="graphicdesign-banners.asp">Rollup Banners</a></li>
              </ul>
          </li>
          <li><a href="#" class="MenuBarItemSubmenu">Consultancy Services</a>
              <ul>
                <li><a href="#">Communications</a></li>
                <li><a href="#">Corporate Image</a></li>
                <li><a href="#">Website evaluation/redesign</a></li>
              </ul>
          </li>
          <li><a href="#.htm">Multimedia</a>
            <ul>
              <li><a href="#">CDROM/DVD</a></li>
              <li><a href="#">2D Animation</a></li>
              <li><a href="#">3D Modeling</a></li>
              <li><a href="#">Powerpoint Presentations</a></li>
            </ul>
          </li>
          <li><a href="#">Online Solutions</a>
            <ul>
              <li><a href="#">Websites</a></li>
              <li><a href="#">Electronic Letterhead</a></li>
              <li><a href="#">Publications</a></li>
              <li><a href="#">Banner Adverts</a></li>
              <li><a href="#">Presentations</a></li>
            </ul>
          </li>
          <li><a href="#">Publishing</a>
            <ul>
              <li><a href="#">ISBN registration</a></li>
              <li><a href="#">Book Binding / Printing</a></li>
              <li><a href="#">Brochure Printing</a></li>
              <li><a href="#">Proofing</a></li>
              <li><a href="#">Academic/Scientific Writing</a></li>
              <li><a href="#">Annual Reports</a></li>
              <li><a href="#">Presentations</a></li>
            </ul>
          </li>
          <li><a href="#">Portfolio</a>
            <ul>
              <li><a href="#">Client List</a></li>
              <li><a href="#">Testimonials</a></li>
              <li><a href="#">Awards</a></li>
            </ul>
          </li>
          <li><a href="links.asp">Partners/Links</a></li>
          <li><a href="contact.asp">About Us</a></li>
		  <li><a href="contact.asp">Contact Us</a></li>
</ul>