CREATE TABLE IF NOT EXISTS `#__downloads_containers` (
  `id` int(255) NOT NULL auto_increment,
  `sequence` int(11) NOT NULL default '0',
  `windowtitle` varchar(255) NOT NULL default '',
  `keywords` varchar(255) NOT NULL default '',
  `parentid` smallint(255) NOT NULL default '0',
  `name` varchar(255) NOT NULL default '',
  `alias` varchar(255) NOT NULL default '',
  `filepath` varchar(255) NOT NULL default '',
  `published` tinyint(1) NOT NULL default '1',
  `description` text NOT NULL,
  `filecount` smallint(6) NOT NULL default '0',
  `foldercount` smallint(6) NOT NULL default '0',
  `icon` varchar(50) NOT NULL default '',
  `registered` tinyint(3) unsigned NOT NULL default '2',
  `userupload` tinyint(3) unsigned NOT NULL default '3',
  `plaintext` tinyint(3) unsigned NOT NULL default '0',
  `groupid` smallint(6) NOT NULL default '0',
  `editgroup` smallint(6) NOT NULL default '0',
  `adminauto` tinyint(3) unsigned NOT NULL default '0',
  `userauto` tinyint(3) unsigned NOT NULL default '0',
  `autogroup` smallint(6) NOT NULL default '0',
  `userid` int(11) NOT NULL default '0',
  UNIQUE KEY `id` (`id`),
  KEY `parentid` (`parentid`,`published`)
) ENGINE=MyISAM;