				CREATE TABLE IF NOT EXISTS `#__downloads_files` (
  `id` int(11) NOT NULL auto_increment,
  `sequence` int(11) NOT NULL default '0',
  `windowtitle` varchar(255) NOT NULL default '',
  `keywords` varchar(255) NOT NULL default '',
  `metatype` smallint(6) NOT NULL default '0',
  `realname` varchar(255) NOT NULL default '',
  `realwithid` tinyint(3) unsigned NOT NULL default '0',
  `islocal` tinyint(3) unsigned NOT NULL default '1',
  `containerid` smallint(6) NOT NULL default '0',
  `userid` int(11) NOT NULL default '0',
  `filepath` varchar(255) NOT NULL default '',
  `filesize` varchar(255) NOT NULL default '',
  `filetype` varchar(255) NOT NULL default '',
  `filetitle` varchar(255) NOT NULL default '',
  `subtitle` text NOT NULL,
  `description` text NOT NULL,
  `smalldesc` text NOT NULL,
  `autoshort` tinyint(3) unsigned NOT NULL default '1',
  `license` text NOT NULL,
  `licenseagree` tinyint(3) unsigned NOT NULL default '0',
  `price` int(11) NOT NULL default '0',
  `currency` char(3) NOT NULL default '',
  `downloads` int(11) NOT NULL default '0',
  `url` varchar(255) NOT NULL default '',
  `icon` varchar(50) NOT NULL default '',
  `published` tinyint(3) unsigned NOT NULL default '1',
  `registered` tinyint(3) unsigned NOT NULL default '2',
  `userupload` tinyint(3) unsigned NOT NULL default '3',
  `download_text` text NOT NULL,
  `recommended` tinyint(3) unsigned NOT NULL default '0',
  `recommend_text` text NOT NULL,
  `featured` tinyint(4) NOT NULL default '0',
  `featured_st_date` date NOT NULL default '0000-00-00',
  `featured_end_date` date NOT NULL default '0000-00-00',
  `featured_priority` smallint(6) NOT NULL default '0',
  `featured_seq` smallint(6) NOT NULL default '0',
  `featured_text` text NOT NULL,
  `opsystem` varchar(50) NOT NULL default '',
  `legaltype` varchar(50) NOT NULL default '',
  `requirements` text NOT NULL,
  `company` varchar(255) NOT NULL default '',
  `releasedate` date NOT NULL default '0000-00-00',
  `languages` text NOT NULL,
  `company_URL` varchar(255) NOT NULL default '',
  `translator` varchar(255) NOT NULL default '',
  `fileversion` varchar(50) NOT NULL default '',
  `fileauthor` varchar(100) NOT NULL default '',
  `author_URL` varchar(255) NOT NULL default '',
  `publish_id` varchar(50) NOT NULL default '',
  `publish_date` date NOT NULL default '0000-00-00',
  `filedate` datetime NOT NULL default '0000-00-00 00:00:00',
  `filehomepage` varchar(255) NOT NULL default '',
  `screenurl` varchar(255) NOT NULL default '',
  `plaintext` tinyint(3) unsigned NOT NULL default '0',
  `isblob` tinyint(3) unsigned NOT NULL default '0',
  `chunkcount` int(11) NOT NULL default '0',
  `groupid` smallint(6) NOT NULL default '0',
  `editgroup` smallint(6) NOT NULL default '0',
  `custom_1` varchar(255) NOT NULL default '',
  `custom_2` varchar(255) NOT NULL default '',
  `custom_3` text NOT NULL,
  `custom_4` int(11) NOT NULL default '0',
  `custom_5` datetime NOT NULL default '0000-00-00 00:00:00',
  `oldid` int(11) NOT NULL default '0',
  `submittedby` mediumint(9) NOT NULL default '0',
  `submitdate` datetime NOT NULL default '0000-00-00 00:00:00',
  `custom_values` text NOT NULL default '',
  UNIQUE KEY `id` (`id`),
  KEY `filetitle` (`filetitle`),
  KEY `url` (`url`),
  KEY `containerid` (`containerid`,`published`),
  KEY `recommended` (`containerid`,`recommended`,`published`),
  KEY `featured` (`containerid`,`featured`,`published`,`featured_st_date`,`featured_end_date`),
  KEY `opsystem` (`containerid`,`opsystem`,`published`),
  FULLTEXT KEY `words` (`filetitle`,`description`,`smalldesc`,`fileauthor`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;