   CREATE TABLE IF NOT EXISTS `#__downloads_repository` (
  `id` int(11) NOT NULL auto_increment,
  `name` varchar(255) NOT NULL default '',
  `alias` varchar(255) NOT NULL default '',
  `sequence` int(11) NOT NULL default '0',
  `windowtitle` varchar(255) NOT NULL default '',
  `keywords` varchar(255) NOT NULL default '',
  `version` char(10) NOT NULL default '',
  `Use_Database` smallint(6) NOT NULL default '1',
  `Main_Page_Title` varchar(100) NOT NULL default '',
  `tabclass` varchar(255) NOT NULL default 'sectiontableentry2,sectiontableentry1',
  `tabheader` varchar(255) NOT NULL default 'sectiontableheader',
  `headerpic` varchar(255) NOT NULL default '$mosConfig_live_site/components/com_remository/images/header.gif',
  `ExtsOk` varchar(255) NOT NULL default 'txt,exe,tar,gz,rar,zip,png,gif,jpg,pdf,doc',
  `ExtsDisplay` varchar(255) NOT NULL default '',
  `ExtsAudio` varchar(255) NOT NULL default '',
  `ExtsVideo` varchar(255) NOT NULL default '',
  `Classification_Types` varchar(255) NOT NULL default '',
  `Scribd` varchar(30) NOT NULL default '',
  `Down_Path` varchar(255) NOT NULL default '$mosConfig_absolute_path/components/com_remository/downloads',
  `Up_Path` varchar(255) NOT NULL default '$mosConfig_absolute_path/components/com_remository/uploads',
  `Large_Text_Len` int(11) NOT NULL default '500',
  `Small_Text_Len` smallint(6) NOT NULL default '150',
  `Small_Image_Width` smallint(6) NOT NULL default '100',
  `Small_Image_Height` smallint(6) NOT NULL default '100',
  `Large_Image_Width` smallint(6) NOT NULL default '600',
  `Large_Image_Height` smallint(6) NOT NULL default '600',
  `MaxSize` int(11) NOT NULL default '5000',
  `Max_Up_Per_Day` smallint(6) NOT NULL default '5',
  `Max_Down_Per_Day` smallint(6) NOT NULL default '5',
  `Max_Down_Reg_Day` smallint(6) NOT NULL default '10',
  `Max_Down_File_Day` smallint(6) NOT NULL default '2',
  `Count_Down` tinyint(3) unsigned NOT NULL default '0',
  `Featured_Number` int(11) unsigned NOT NULL default '0',
  `Max_Up_Dir_Space` int(11) NOT NULL default '50000',
  `Favourites_Max` smallint(6) NOT NULL default '5',
  `Max_Thumbnails` smallint(6) NOT NULL default '0',
  `Min_Comment_length` smallint(6) NOT NULL default '1',
  `Make_Auto_Thumbnail` tinyint(3) unsigned NOT NULL default '0',
  `Default_Version` char(20) NOT NULL default '',
  `Main_Authors` text NOT NULL,
  `Author_Threshold` smallint(6) NOT NULL default '0',
  `Date_Format` char(20) NOT NULL default '',
  `Set_date_locale` varchar(20) NOT NULL,
  `Force_Language` varchar(20) NOT NULL,
  `Show_all_containers` tinyint(3) unsigned NOT NULL default '0',
  `Anti_Leach` tinyint(3) unsigned NOT NULL default '0',
  `Allow_Up_Overwrite` tinyint(3) unsigned NOT NULL default '1',
  `Allow_User_Sub` tinyint(3) unsigned NOT NULL default '1',
  `Allow_User_Edit` tinyint(3) unsigned NOT NULL default '1',
  `Allow_User_Delete` tinyint(3) unsigned NOT NULL default '0',
  `Allow_User_Up` tinyint(3) unsigned NOT NULL default '1',
  `Enable_Admin_Autoapp` tinyint(3) unsigned NOT NULL default '1',
  `Enable_User_Autoapp` tinyint(3) unsigned NOT NULL default '0',
  `Allow_Comments` tinyint(3) unsigned NOT NULL default '1',
  `Allow_Votes` tinyint(3) unsigned NOT NULL default '1',
  `Allow_Large_Images` tinyint(3) unsigned NOT NULL default '1',
  `Activate_AEC` tinyint(3) unsigned NOT NULL default '0',
  `Remository_Pathway` tinyint(3) unsigned NOT NULL default '0',
  `Enable_List_Download` tinyint(3) unsigned NOT NULL default '0',
  `Audio_Download` tinyint(3) unsigned NOT NULL default '0',
  `Video_Download` tinyint(3) unsigned NOT NULL default '0',
  `User_Remote_Files` tinyint(3) unsigned NOT NULL default '0',
  `See_Containers_no_download` tinyint(3) unsigned NOT NULL default '1',
  `See_Files_no_download` tinyint(3) unsigned NOT NULL default '1',
  `Show_RSS_feeds` tinyint(3) unsigned NOT NULL default '1',
  `Allow_File_Info` tinyint(3) unsigned NOT NULL default '1',
  `Show_Footer` tinyint(3) unsigned NOT NULL default '1',
  `Show_File_Folder_Counts` tinyint(3) unsigned NOT NULL default '1',
  `Send_Sub_Mail` tinyint(3) unsigned NOT NULL default '1',
  `Sub_Mail_Alt_Addr` varchar(255) NOT NULL default '',
  `Sub_Mail_Alt_Name` varchar(100) NOT NULL default '',
  `Time_Stamp` varchar(15) NOT NULL default '1119386419',
  `Profile_URI` varchar(255) NOT NULL,
  `download_text` text NOT NULL,
  `preamble` text NOT NULL,
  `Default_Licence` text NOT NULL,
  `customizer` text NOT NULL,
  `custom_names` text NOT NULL,
  UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM;
